method: evrepsl
dataset:
  save_to: /path/to/datasets/ncaltech101
representation:
  height: 180
  width: 240
  max_events: 50000
  in_channels: 5
epochs: 100
batch_size: 32
lr: 0.0001
weight_decay: 0.0001
seed: 42
